kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."${kind_registry_hostname}:${kind_registry_port}"]
    endpoint = ["http://${kind_registry_hostname}:${kind_registry_port}"]
nodes:
  - role: control-plane
    extraPortMappings: # these expose the various node ports to the dev container's host (windows)
      - containerPort: ${TF_VAR_sftp_nodeport}
        hostPort: ${TF_VAR_sftp_nodeport}
        protocol: TCP
      - containerPort: ${TF_VAR_database_nodeport}
        hostPort: ${TF_VAR_database_nodeport}
        protocol: TCP
      - containerPort: ${TF_VAR_website_nodeport}
        hostPort: ${TF_VAR_website_nodeport}
        protocol: TCP
